apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: frontend  
  namespace: devbcn-demo
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      app: frontend  
  template:  
    metadata:  
      labels:  
        app: frontend  
    spec:  
      containers:  
        - name: frontend  
          image: docker.io/mariiasharkovska/application-frontend-x:v1
          ports:  
            - containerPort: 80